### ISSUE TITLE
Use Application instead of FakeApplication

### ISSUE THREAD

**Issue by thesamet** [scalatest/scalatestplus-play#24]
In Play 2.4, it is very easy to create Application instances for test using `GuiceApplicationBuilder`. At the same time, `FakeApplication` has several constraints on the objects it can create (for example, it can't override Guice modules).

Now, that FakeApplication extends Application,  it would be better to use `Application` in traits like `OneAppPerTest`.

**Comment by bvenners** [comment]
We did this quite a long time ago. Let me track down the release number and I'll post it here.

**Comment by cjwebb** [comment]
#21 mentioned the same thing, and says that release number 1.4.0-M4 contains the change.
I can confirm that it is working.

**Comment by thesamet** [comment]
1.4.0-M4 has it. Thanks!

**Comment by regispl** [comment]
Hey guys, what's the story with that Issue? I can see that in other issue @bvenners wrote:

> I have released 1.4.0-M4 with FakeApplication changed into Application.

But when I'm looking at master branch I can still see app being FakeApplication rather than Application in e.g. OneAppPerSuite:

https://github.com/scalatest/scalatestplus-play/blob/c67715398ffaea9c0131fb39937f0823e3d3a0e0/src/main/scala/org/scalatestplus/play/OneAppPerSuite.scala#L126

Is this something that's going to be fixed by any chance? If not, what's the other, nice way I can build my own Application using Guice Builder and use it together with ScalaTest+Play?

**Comment by cjwebb** [comment]
Good question.

1.4.0-M4 definitely has the change, and is working. I'm using that version. I'm not sure how to find the corresponding commits on Github, but you can download and inspect the sources from Maven Central.
http://search.maven.org/#artifactdetails%7Corg.scalatestplus%7Cplay_2.11%7C1.4.0-M4%7Cjar

Maven Central also have a version 1.5.0-SNAP1, but that doesn't have the change :( Hopefully whenever a new final version is published it'll all be okay!

**Comment by regispl** [comment]
Thanks, it seems to be fixed there, cool!
It looks like the 1.4.0 release is based on wip-play-2.4 branch and that change is applied there :+1: 

https://github.com/scalatest/scalatestplus-play/blob/wip-play-2.4/src/main/scala/org/scalatestplus/play/OneAppPerSuite.scala#L126
